Fixed not get clients and products in summary seller
CristopherAreche/crm-front pull request #161
Opened 2023-04-18 20:03 UTC by matias-d

2023-04-18 20:42 UTC, CristopherAreche requested changes
Por favor hazte un pull de los últimos cambios y vuelve a crear el pull request. 😎

2023-04-18 21:28 UTC, Macarr submitted a review, later dismissed

2023-04-18 21:37 UTC, pikachu007 approved these changes

2023-04-18 21:38 UTC, RicardoGT0 approved these changes

2023-04-18 21:39 UTC, gxspxr approved these changes

2023-04-18 21:41 UTC, matias-d commented
> Por favor hazte un pull de los últimos cambios y vuelve a crear el pull request. sunglasses

Ya esta bro

2023-04-19 17:35 UTC, CristopherAreche approved these changes

2023-04-19 17:35 UTC, merged